imports:
  - path: minecraft_vm.py
  - path: minecraft_storage.py

resources:
  - name: server
    type: minecraft_vm.py
    properties:
      region: europe-west4
      zone: europe-west4-c
      startup-script: |
        #!/bin/bash
        mkdir -p /home/minecraft
        mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/disk/by-id/google-minecraft-disk
        mount -o discard,defaults /dev/disk/by-id/google-minecraft-disk /home/minecraft

        apt-get update
        apt-get install -y default-jre-headless

        cd /home/minecraft
        wget https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar
        java -Xms2G -Xmx7G -d64 -jar server.jar nogui
        sed -i 's/false/true/g' eula.txt

        # adjust the RAM settings to the instance type
        apt-get install -y screen
        screen -dmS mcs java -Xms2G -Xmx7G -XX:+UseG1GC -d64 -server -jar server.jar nogui

        cat << EOF > backup.sh
        #!/bin/bash
        screen -r mcs -X stuff '/save-all\n/save-off\n'
        /usr/bin/gsutil cp -R ${BASH_SOURCE%/*}/world gs://$(ref.storage.bucket)/$(date "+%Y%m%d-%H%M%S")-world
        screen -r mcs -X stuff '/save-on\n'
        EOF

        chmod 755 /home/minecraft/backup.sh
        crontab -l > mycron
        echo "0 */4 * * * /home/minecraft/backup.sh" >> mycron
        crontab mycron
        rm mycron

  - name: storage
    type: minecraft_storage.py
    properties:
      location: EU